conditions: v1
version: "= 0"
if: >  # Forbid running non-PR pushes from pyup bot
  not (type != pull_request AND branch =~ ^pyup\-scheduled\-update\-)

dist: xenial

language: python

python:
- 3.5
- 3.6
- &mainstream_python 3.7
- 3.8-dev
- &pypy3 pypy3.5-6.0.0

install:
- &upgrade_python_toolset pip install --upgrade pip wheel setuptools
- pip install -r requirements/ci.txt

script:
- make cov-ci-run

after_success:
 - codecov

_helpers:
- &_mainstream_python_base
  python: *mainstream_python
- &_reset_steps
  env: []
  before_install: skip
  install: skip
  script: skip
  after_success: []
- &_lint_base
  stage: &doc_stage_name docs, linting and pre-test checks
  <<: *_mainstream_python_base
  <<: *_reset_steps
  install:
  - *upgrade_python_toolset
  - pip install -U -r requirements/ci.txt
- &_doc_base
  <<: *_lint_base
  install:
  - *upgrade_python_toolset
  - pip install -U -r requirements/doc.txt -r requirements/doc-spelling.txt
  after_failure: cat docs/_build/spelling/output.txt
  addons:
    apt:
      packages:
      - libenchant-dev

os: linux

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.8-dev

  - <<: *_doc_base
    name: Checking docs spelling
    script:
    - make doc-spelling

  - <<: *_doc_base
    name: Checking Towncrier fragments
    install:
    - *upgrade_python_toolset
    - pip install -r requirements/ci.txt
    - pip install -r requirements/towncrier.txt
    script:
    - towncrier --yes

  - <<: *_lint_base
    name: Linting source code with flake8
    install:
    - *upgrade_python_toolset
    - pip install -r requirements/flake.txt
    script:
    - flake8 aiosignal tests

  - <<: *_lint_base
    name: Linting source code with mypy
    install:
    - *upgrade_python_toolset
    - pip install -r requirements/ci.txt
    script:
    - mypy aiosignal

  - <<: *_lint_base
    name: Verifying distribution package metadata
    install:
    - *upgrade_python_toolset
    - pip install -r requirements/ci.txt -r requirements/doc.txt
    script:
    - python setup.py --verbose sdist bdist_wheel
    - twine check dist/*

  - <<: *_lint_base
    name: Making sure that CONTRIBUTORS.txt remains sorted
    language: shell
    install:
    - skip
    script:
    - LC_ALL=C sort -c CONTRIBUTORS.txt


deploy:
  provider: pypi
  username: __token__
  password:
    secure: qmyq5Qr0tF0ak/2IS5dBTTmX7WIysbOg2WuBfIrx44IPYbqAqIV+vxN7WtcZurHPJqplNuaU2eWiHKg68x1hiLPxGQmnxwn938tNJ147XCRDL9IPLcLQEfssUIWBbZE0bXaHJcdybYg6YaryR1d7lSewInQ6i51BxhQDFfB9hr4NUEM9yoN5XzvFLq5EsHuXL3IQPe3Rn07QebRPJhekk++FwgWB487TBF1sx8rbFpvBoNiE7X1tFnyTjZTl4eyPHo/3cTpzhO8cdELgnO0Ux9wHjhvhywK2oh0Ct49D4NnZ1eM2mrHiBxR/9pYC7N4pStTReqELjk2Cr9JS8dzRO0NWzZL+ElMVpLbVhJauYlG570sIPaauBhy40dy+hrjqCtMjrJsbt9kpugmEyYpKt9nKWGxcGvuwepOYyQmE/5iT/Ox8g+m07G4SYksP0lEUPmsXtrtRMr6hRmBuBCYGN4Sv1c+K+rdRL5OdLA8QuSRceNXCf9StF5BJPYTg5X6cLj99Lb9KLKnMJg6VkBx8ovBPpghALeNul/D41kjV1azx4RP7kKD4e1LzfAO8uOITudiCfFyBawXDbiNeaeACy4YniCTwZvC++sgTMPEP3cbqviunLe5EiNabjb2GxxtGXmIahu3NNFw+FreYacWdj9N/Zc1T4SH6HIaQybF3SuU=
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    <<: *_mainstream_python_base
    tags: true

stages:
- *doc_stage_name
- test
- deploy

cache: pip

before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
